### ISSUE TITLE
Expose more parameters via resource XMLs

### ISSUE THREAD

**Issue by anthonynosek** [wdullaer/MaterialDateTimePicker#10]
The displayed calendar dates (numbers) and currently focused hours or minutes should have a slightly larger font size. Just slightly as they appear a little too small and should be differentiated from the remaining text. Happy to discuss.

**Comment by wdullaer** [comment]
Can you post a screenshot on how you'd like it to be, compared to how it is now?
I'm happy with the current font sizes, but it might all render slightly different on different devices.

**Comment by anthonynosek** [comment]
Parameters, it's all about parameters. We could introduce a font size (and color) parameter for the calendar. And whilst we're adding parameters a string for the "Done" button text!

But let me have a think about exact changes. I know it was my initial thought upon seeing the picker. If I still think it requires a change after a couple of days I'll let you know and will provide more information.

**Comment by wdullaer** [comment]
I'm not sure I agree with the premise that everything should be a parameter. Especially not if it's an open source project. If your change is too niche, you should fork rather than make it a parameter.

That said: the things you are looking for are already parameters. Take a look at `/res/values/colors.xml` and `/res/values/dimens.xml`
You can overwrite any of those values in your project style file.

**Comment by anthonynosek** [comment]
Given that I'd be looking to override the time_picker_selector?
I am aware of the color parameters, they simply aren't extensive enough.

**Comment by wdullaer** [comment]
Rather than changing the colour, you might want to change the opacity of the selector (like the original google picker).
This is currently a hardcoded value.
I'll see if I can add both of those as an xml parameter next time I revisit this.

I also think I've found a way to make the text white when you exactly select the value. This should make things work for hours and most of the common minutes use cases. It requires a bit of work though, and I'm short on time at the moment, but I'll get around to it eventually.

**Comment by anthonynosek** [comment]
Thanks, I look forward to any future updates.
If I have time (limited also at the moment) I'll fork the project.
