### ISSUE TITLE
[Bug] TimePicker title isn't dark

### ISSUE THREAD

**Issue by geecko86** [wdullaer/MaterialDateTimePicker#103]
Even though mdtp_accent_color_dark is set, the top of the dialog isn't dark. 
This only occurs with 1.5+, not with 1.4.2.

![screenshot](https://i.imgur.com/WdBktmF.jpg)

**Comment by wdullaer** [comment]
You've hit the bug I spotted earlier.

Your code is now in the case where it no longer uses mdtp_accent_color, but uses either android.R.attr.colorAccent (lollipop+) or R.attr.colorAccent (support library).
There's a bug where it will apply colorAccent rather than the programmatically darkened version of it.

I'll try to release a new version today or tomorrow

**Comment by Aryan-mor** [comment]
Please bug fix.
TimePickerDialog does not support `setAccentColor` function;

**Comment by wdullaer** [comment]
If you have a problem, please create a new issue rather than trying to resurrect ancient ones.
As far as I can tell this functionality is working just fine in the latest version
