### ISSUE TITLE
timePicker fragment sample

### ISSUE THREAD

**Issue by thinkpozzitive** [wdullaer/MaterialDateTimePicker#134]
Could you provide a timePiker fragment sample that works similar to http://developer.android.com/guide/topics/ui/controls/pickers.html#TimePickerFragment?

**Comment by wdullaer** [comment]
Can you be a bit more specific about what is not clear?

There's a section in the README on how this library works and a demo app you can inspect as well.

**Comment by thinkpozzitive** [comment]
So if you've got a fragment like (taken from the afficial documentation: http://developer.android.com/guide/topics/ui/controls/pickers.html#TimePickerFragment):

   public static class TimePickerFragment extends DialogFragment
                            implements TimePickerDialog.OnTimeSetListener {

    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        // Use the current time as the default values for the picker
        final Calendar c = Calendar.getInstance();
        int hour = c.get(Calendar.HOUR_OF_DAY);
        int minute = c.get(Calendar.MINUTE);

        // Create a new instance of TimePickerDialog and return it
        return new TimePickerDialog(getActivity(), this, hour, minute,
                DateFormat.is24HourFormat(getActivity()));
    }

    public void onTimeSet(TimePicker view, int hourOfDay, int minute) {
        // Do something with the time chosen by the user
    }
   }


And in an activity:

    public void showTimePickerDialog(View v) {
    DialogFragment newFragment = new TimePickerFragment();
    newFragment.show(getSupportFragmentManager(), "timePicker");
    }

you cannot modify the fragment to return 

    return TimePickerDialog.newInstance(this, hour, minute,
                DateFormat.is24HourFormat(getActivity()));

because it expects the type to be returned a DialogFragment not a com.wdullaer.materialdatetimepicker.time.TimePickerDialog.

Note: I should note I'm a beginner at this, and I'm sure the answer is simple but...

**Comment by wdullaer** [comment]
While this library is similar to the official pickers, they are not API compatible. This means you can't expect the documentation of the SDK pickers to work without change for this library.

The Picker classes in this library are already `DialogFragments`.
This means you do not need to implement a DialogFragment yourself.

Just call `tpd = TimePickerDialog.newInstance(...)`
and then `tpd.show(getFragmentManager(), "sometag");`

Also note that the Pickers inherit from normal Fragments, rather than support library Fragments, so you'll need to use `getFragmentManager()`.

Go through the README and take a look at the included sample app for inspiration.

Unfortunately android development is not very forgiving for newcomers :(

**Comment by thinkpozzitive** [comment]
Thanks for the quick reply. 

"Just call tpd = TimePickerDialog.newInstance(...)" is what I ended up doing and got it working.

**Comment by minghan1219** [comment]
Hi, may i know how to implement this datepicker inside my dialog fragment?
