### ISSUE TITLE
TimePicker not maintaining last selected time when re-opened

### ISSUE THREAD

**Issue by jonamreddy** [wdullaer/MaterialDateTimePicker#168]
1. Initialize TimePicker dialog
2. Show dialog
3. Select a time and close dialog
4. Re-show dialog

**Expected**
`Will reopen to the last picked date`

**Actual**
`Will open to the initialized time`

**Note**
A new instance is **_not created_** each time to show the TimePicker. It is initialized once and the **_show_** is called to reopen.

**Comment by wdullaer** [comment]
Well your note does say why this happens.
The library assumes you create a new instance every time.

**Comment by jonamreddy** [comment]
But, why does this work in the DatePicker?

**Comment by wdullaer** [comment]
Because they different on the inside.
I'm not saying this cannot be done, I'm saying I'm not supporting it right now.
I don't test the cases where you reuse the instances. There might a number of other subtle issues.

I don't test them because I don't know why you would keep them around. Why not just create a new instance every time? Lazy loading results in much better performance generally.

**Comment by jonamreddy** [comment]
Thanks wdullaer. It's just for consistency. Having the DatePicker supports this and the TimePicker not supporting, I thought it was something to be fixed.

Recreating instance each time and using the selected time for initialization. Works like a charm!

Thanks!
