### ISSUE TITLE
Could not find support-v4.jar

### ISSUE THREAD

**Issue by nikolleto** [wdullaer/MaterialDateTimePicker#250]
Hi. I have got those dependencies in build.gradle file:

```
    compile 'com.android.support:design:24.0.0'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:cardview-v7:24.0.0'
```

When I'm adding your library, I'm getting an error on project sync.

```
Error:A problem occurred configuring project ':app'.
> Could not find support-v4.jar (com.android.support:support-v4:24.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/24.0.0/support-v4-24.0.0.jar
```

Can I use this library with com.android.support library version 24 or higher?

**Comment by wdullaer** [comment]
There shouldn't be any issue with that.
The library itself relies on a v23 version of the support library at the moment

The error also seems to be more around the fact that maven couldn't get the library from the jcenter server. Maybe you had some network issues when running the build? (not noticing it previously because all dependency results were cached)

**Comment by spartacus777** [comment]
The same error. Anyone managed to fix it?

**Comment by nikolleto** [comment]
Yep, I've downloaded a library and manually changed few lines in build.gradle

**Comment by wdullaer** [comment]
Does this still happen in version 3.0.0
I've updated the dependencies, which hopefully resolves conflicts like this
