### ISSUE TITLE
onTimeSet return null tag

### ISSUE THREAD

**Issue by alhazmy13** [wdullaer/MaterialDateTimePicker#261]
Hi there, 
there's an issue with `onTimeSet` call back, it's return a null tag even if pass it with show method 
`tpd.show( mContext.getFragmentManager(), "MyTag");`

```
@Override
    public void onTimeSet(RadialPickerLayout view, int hourOfDay, int minute, int second) {
        Log.d(TAG, "onTimeSet: "+view.getTag()); // onTimeSet: null
}
```

**Comment by alhazmy13** [comment]
fixed with pull request number #262

**Comment by wdullaer** [comment]
This is due to the fact that it returns the `RadialPickerLayout` rather than the `TimepickerDialog`.
This is a relic of the google library that I forked to create this.

Unfortunately changing this touches the public API which makes it a semver major change.
I have made this change in the branch for the next major release.

**Comment by wdullaer** [comment]
Fixed in v3
