### ISSUE TITLE
Not usable with android.app.v4.FragmentManager

### ISSUE THREAD

**Issue by Leandros** [wdullaer/MaterialDateTimePicker#30]
It doesn't support the support FragmentManager, only the native. Using the support FragmentManager is encouraged.

**Comment by wdullaer** [comment]
This library only supports Android 4.0 and up (in fact I think I'll need to bump the min SDK version even higher). Fragments are available here.
Even if you are using the SupportFragment manager in other places you can show this dialog using the standard FragmentManager. The call will work. This is in fact what I am doing in my own app without issues.

Moving the SupportFragmentManager is actually more annoying, because that would mean everyone who'd want to use this library needed to use support classes, while with the current setup it's optional.

Check #8 for more info

**Comment by Leandros** [comment]
Even when it supports only 4.0 an up, it's actually encouraged by Google to use the v4.FragmentManager (unless you're **only** targeting the latest and greatest OS, but in this case you don't need this library anyway).

**Comment by KlausConrado** [comment]
Another good reason is that Fragment.getChildFragmentManager() is from API 17 and i use the support library version just because of that (my app is also 4.0 and up).
I want to use your lib but i can't stop using ChildFragmentManager. So please, change the fragments to the support library API.

Thanks

**Comment by wdullaer** [comment]
I'm sorry, but I'm not going to break the API for everyone using this.

While the code change is minor, the impact on the apps using the library is big.
It should be fairly straightforward to maintain a fork with just that change though.

**Comment by chanakin** [comment]
Humbly going to submit that updating the library to a version that uses support fragments isn't going to hurt anyone using the old version of the library. It's industry standard for Android developers to use the support library for fragments, even for those of us who are supporting only OS versions that support native fragments. 

And I'd be shocked if there were developers out there with apps that don't use the support library in some way or another. That would be a very limited use case app indeed....

**Comment by wdullaer** [comment]
As mentioned in the [FAQ](https://github.com/wdullaer/MaterialDateTimePicker#faq) and numerous other issues, I do not intend to change this.

Regardless of your stance on the use of support fragments, changing this now would be a breaking API change. It would force everyone to use an old version or do a sizeable refactoring, for a change which is at best a step sideways.

If you really feel so strongly about this, feel free to maintain a fork (or take a look in the network, some people already do just this). It's just a tiny change to the code and would be easy to keep up to date with the upstream.

**Comment by chanakin** [comment]
I'm aware of your stance, and I'm saying that I don't believe your arguments are sufficient justification to not change. It's, as you say, two lines of code to move over to use the support library. All of the existing consumers of this library will have to update to the new library consciously at some point anyways, and there's absolutely no benefit to using native fragments over the support library ones; it's also minimal change on the consumers' part to move to support fragments, and I daresay might actually simplify many developers' lives because they don't have to do potentially dangerous workarounds like combining support and native fragments in their apps. If anything, I'd say there's a definite disadvantage, because any bugs that are found in the native Fragment class won't get repaired for any devices that are running the buggy version of the OS with that particular implementation. Not to mention the fact that support fragments include the ability to nest fragments with getChildFragmentManager(), which is not available until API 17, and this library is reported to support 4.0+, so you've already crippled some developers who have architecture that involves nesting fragments and forced them to branch.

For the record, I've already branched it on my own. I'm merely making the argument that this shouldn't be a branch feature. This should be a part of the library itself.

**Comment by osrl** [comment]
@chanakin explained it all. I'm also going to insist on that
