### ISSUE TITLE
setDisabledDays causes dialog taking long time to display

### ISSUE THREAD

**Issue by CollinDai** [wdullaer/MaterialDateTimePicker#304]
In my current app there are over 150 days that need to be disabled.

When using `setDisabledDays()` before calling `datePickerDialog.show(..)`, the dialog takes around 8 seconds to display. The memory monitor shows extreme usage and gc happened twice during the process (see below image)

![with setDisabledDays](https://cloud.githubusercontent.com/assets/1173211/22221854/9b1c0e02-e182-11e6-8da8-de97ff575900.png)

If I commented the `setDisabledDays()`, the dialog takes less than one second to show and the memory consumption is barely noticeable.

Thanks~

**Comment by wdullaer** [comment]
This is to be expected.
The disabled days is stored as an array of calendar objects which need to be iterated over multiple times per date that is rendered.
It tries to shortcircuit the comparison, but if the majority of your disabled days is before the rendered date, you will still hit the worst case scenario.

The current logic is really not intended for big sets of disabled dates.
Performance could probably be improved by saving the disabled dates in a hashmap (or another structure with O(1) lookups), so that we don't need to iterate the full array for every date.
Similarly memory usage could be improved by trying to reuse the same Calendar object when comparing, rather than creating a new one each time (I don't think I'm caching).

In your case, it seems like you want to disable roughly half a year. I'm guessing you have some logic that drives whether a date is disabled. You could extend the picker in this class and overwrite `isOutOfRange()` with your logic, rather than exploding the logic into an array of `Calendar`s and using `setDisabledDays()`.

**Comment by CollinDai** [comment]
Hi @wdullaer thanks for the detailed answer. Overwriting `isOutOfRange()` works great to me.

The 150 disabled days are not all from the same year. And they are returned from the server so it's a static list of dates. I ended up creating a `HashSet` to avoid iterating the list. And if it contains the customized date object then `isOutOfRange()` returns true. So performance is not too bad.
