### ISSUE TITLE
Check that date is not out of range before calling onDateSet

### ISSUE THREAD

**Issue by razielsarafan** [wdullaer/MaterialDateTimePicker#326]
I have disabled every date before today in my Dialog.

An user can pick a future date, change the year to a past year and then click ok, and the Dialog won't check if the selected date is out of range and will give me an invalid value. This can be circumvented by adding a call to isOutOfRange in notifyOnDateListener, but it can't be fixed by extending DatePickerDialog because mCalendar is private. Even a getter in mCalendar would allow me to fix this easily from my custom Dialog.

**Comment by wdullaer** [comment]
Can I ask how you did this? Which method did you use to disable the days?

Because if you use setMinDate to disable all dates before a given date, the picker will disable all year selections before the current year, and even if you use the trick to roll the year forward and then backward, the selected date will be rounded up to the nearest selectable date.

The logic that limits the year selection does not take setDisabledDays into account, because the assumption is that this method will be used to disable a limited selection of days. But even in that event if you change the year selection, the date will be rounded to the nearest date that is selectable according to the setup you have done

**Comment by Jesusrz001** [comment]
This works as intended with setDisabledDays.

**Comment by wdullaer** [comment]
In fact overriding `isOutOfRange` is not sufficient for all functionality to work properly.
I'm thinking of putting all that logic in an interface, so it's clear which methods need to be implemented to have a custom date range logic.
