### ISSUE TITLE
OnDateChangedListener isn't public in 3.1.3

### ISSUE THREAD

**Issue by alinavoronkova** [wdullaer/MaterialDateTimePicker#337]
Hi!
I'm developing something like "week picker" calendar. And so I need to use my own WeekPickerDialog. In the last version 3.0.0. (which I used) the interface 
 OnDateChangedListener was public, but after update I figured out that it has package access only. 

Could you make it public, please?

**Comment by wdullaer** [comment]
I changed this because people were using it as a callback to get the date and then opened tickets when it didn't work as expected.
I think protected should do what you want (it will not prevent people from using it as a callback, but hopefully protected should get the message across that this is an internal method)

**Comment by alinavoronkova** [comment]
Thanks, I'll be waiting for the update.
