### ISSUE TITLE
Date & Time Format

### ISSUE THREAD

**Issue by hatamiarash7** [wdullaer/MaterialDateTimePicker#353]
can i use this lib with Hijri Date or Time ???? or we should use only Gregorian ?

**Comment by wdullaer** [comment]
The library is focused on Western date and time formats, because that is what I know.
As much as I would love to, I'm not intimately familiar with all cultures and languages around the world.

Someone has forked this library to the Persian calendaring system.
You are free to do the same.

In case it can be trivially extended to support Hijri dates and times, I take pull requests.
