### ISSUE TITLE
setDisabledDays does not work if the calendars have had their time zone changed.

### ISSUE THREAD

**Issue by DavidCG** [wdullaer/MaterialDateTimePicker#383]
The app that I am working on stores its time stamps in a weird format, so we're having to jump through some hoops to get the disabled dates to line up correctly.  If I set the time zone of the disabled calendar to UTC, the date picker no longer makes the dates un-selectable.  I tried setting the time zone of the date picker to UTC as well, but nothing changed.  It works if I do not try to set the time zone, but this means I will have to do some manipulation ahead of time to make it work.

Also, is there any plan to make this dialog support joda-time objects?  Calendars can get you there, but they're pretty clunky and awkward.  

Overall, I like the library a lot.  We're getting ready to fix the time stamps that our app uses, so this will stop being and issue for us in the future, but it's causing some unfortunate problems right now.

**Comment by wdullaer** [comment]
I have no plans to use joda-time.
I haven't needed it so far and I would like to avoid pulling in additional dependencies (version management of the jvm is not really elegant).
It would probably also be a serious refactor on a library I have barely enough time for as it is.

That said: I am curious about your issue. If you set the picker to UTC and the disabled dates to UTC then things should normally need to work (it is comparing `Calendar`s internally). I will need to review the setTimeZone feature, because I did not write that myself.

Do you have a small code sample that I can use to reproduce the issue?
Or can you write a test for the DefaultDateRangeLimiter that exposes this behaviour?
