### ISSUE TITLE
Cannot change DatePickerDialog to custom timezone

### ISSUE THREAD

**Issue by johnmarktagle** [wdullaer/MaterialDateTimePicker#398]
You are setting the mCalendar in DatePickerDialog at initialisation using the current/default system Timezone.
private Calendar mCalendar = Utils.trimToMidnight(Calendar.getInstance(this.getTimeZone()));

So even if we set a custom timezone at DatePickerDialog.newInstance(), the dialog calendar is already using the system timezone.

Only way to resolve this by far is to change the system timezone to custom timezone.

AlarmManager alarm = (AlarmManager) getSystemService(Context.ALARM_SERVICE);
alarm.setTimeZone(timezone);

But this is not a very good solution since don't want to touch any user device defaults. 

We just need to to change to custom timezone inside our app.

**Comment by wdullaer** [comment]
There is a `setTimeZone()` method. This will also set the TimeZone of the internal Calendar that keeps track of the state.
However, the initial date is passed in through the `newInstance` method, so it might be off unless you do some compensation for it.

Would it solve your issue if I made an extra `newInstance` method which takes a Calendar?
This would then initialize the first selection and the timezone based on that Calendar instance.

**Comment by johnmarktagle** [comment]
That would be perfect. I am working on an app that needs to be fixed for a certain timezone, irregardless of the device timezone.

**Comment by jerry33** [comment]
Is this already solved? I'm working on an app that allows user to pick a date for a trip (from array of specific days) but with time zone belonging to the place where the trip actually is, not what default settings user has in his device. For example, if the trip is in Japan, and it's on November 28 in the morning in Japan, I will only be able to pick November 27, because currently I'm in Europe and so is my device set up. Thanks for the reply.

**Comment by wdullaer** [comment]
This hasn't been solved yet, but I have been thinking about it.
I am wondering how much of an issue this is. The callback returns integers and not Calendar objects. So in theory the picker could be blissfully unaware of the mess that is timezones, and you can apply the correct timezone when you construct a Calendar from the result of the callback.
Similarly when initializing, if you get the initial date as a Calendar, you can set the timezone to the correct location before extracting the values.
It then won't really matter what timezone the picker itself is operating in.

Does this look reasonable to you? What did I miss?

**Comment by jerry33** [comment]
I found a workaround for this. I was using `setTimeZone()` for `DatePickerDialog`. My idea was to set information about time zone to `DatePickerDialog` when initializing it and then retrieve it in callback using `getTimeZone()`. The problem appeared when I tried to use it together with `setSelectableDays()`. I don't know what exactly the problem was, but it caused a very strange behavior, for example if I put two days as selectable ones, I could only pick one of them. Or I couldn't even pick any if using this method. So I completely get rid of this method and put this information about time zone right into the Fragment bundle using `setArguments()` method. Now, Dialog has no clue about time zone used when adding selectable days (Calendar is being created from year, month and day without any time zone added) and I'm passing this information over Bundle.

Anyway, you might investigate what exactly the problem is with `setTimeZone()` method as it clearly doesn't work properly with `setSelectableDays()`.

**Comment by jerry33** [comment]
![screenshot_20171207-121151](https://user-images.githubusercontent.com/8707669/33712504-ffcf8f44-db47-11e7-9fc6-d3005b6e97a1.png)
![screenshot_20171207-121207](https://user-images.githubusercontent.com/8707669/33712511-022b2fd2-db48-11e7-85e9-53921372d0b6.png)

As you can see in these screenshots. I used method `datePickerDialog.setTimeZone(java.util.TimeZone.getTimeZone("America/Los_Angeles"));` (living in Europe) and passed three Calendar objects as selectable days (day 2, 6 and 8). As you can see, after opening Dialog, day 8 is selected by default (but it's grey, not black), but when you change it, you can't pick it again. After removing this line of code, everything works fine, but you don't have a clue what time zone you want to use in `onDateSet()` callback. That's why I used Fragment arguments.

**Comment by wdullaer** [comment]
I'm thinking of just completely removing the setTimeZone method.
I need to review the code, but if I can make the picker completely unaware of the timezone's that would be ideal.
You can then do the proper conversions in the initialization and callback code.
I just need to think about how I handle the range limiting options as those take Calendar objects, which might have a Timezone different than the default one.
