### ISSUE TITLE
Could not get unknown property 'ANDROID_BUILD_SDK_VERSION

### ISSUE THREAD

**Issue by Birdielove** [wdullaer/MaterialDateTimePicker#407]
whenever i try to import the library i get this error
Error:(4, 1) A problem occurred evaluating project ':DatePicker'.
> Could not get unknown property 'ANDROID_BUILD_SDK_VERSION' for project ':DatePicker' of type org.gradle.api.Project.

**Comment by wdullaer** [comment]
Are you using gradle?

**Comment by Birdielove** [comment]
yes

**Comment by wdullaer** [comment]
Do you have some special rules set?

The libraries build.gradle loads values from a gradle.properties file. That's where the `ANDROID_BUILD_SDK_VERSION` property lives. It seems like this variable is not initialized when you try to build.
My guess (and I'm absolutely no gradle expert) is that you're excluding this gradle.properties file somehow.

**Comment by Birdielove** [comment]
Asa i know i don't have any specific rules and gradle.properties file is included, btw you have a look at my project here https://github.com/Birdielove/To-Do.git, thanks for your help really appreciated.

**Comment by wdullaer** [comment]
I'm sorry, I'm not going to debug your project. I just don't have the time.
The cheapo solution (most likely) is to just define the variable in your `gradle.properties`.

I'm no gradle expert. I dread upgrading it, because each time any component anywhere changes my build blows up.
I suggest reading up on how gradle handles inheriting properties from dependencies to get to the bottom of this.
