### ISSUE TITLE
support for returning an instant

### ISSUE THREAD

**Issue by huntj88** [wdullaer/MaterialDateTimePicker#432]
could we get support for Java 8 instants (available in API 26) and/or Jake Wharton's backport? 
https://github.com/JakeWharton/ThreeTenABP

preferably both, especially since the API on both of them are identical and it would give much more flexibility to the library.

**Comment by wdullaer** [comment]
This is highly unlikely.
The callbacks return plain integers of the components that were selected. The Timepicker is internally not even aware of time as such.
I did merge some features which allow you set a Timezone on the Datepicker, but I'm starting to believe that was a mistake.
I'd like to keep these Dialogs as dumb as possible. If special timezone requirements are needed, you can use these classes outside of the pickers. As I mentioned, the callbacks just give you integers, which you can then use to construct the proper objects (taking into account your apps context).

The problem is just too hard, so as a proper engineer I'm going to try to design it such that I don't need to solve it ;-)

I hope my reasoning makes sense
