### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by nguyenhuutho** [wdullaer/MaterialDateTimePicker#442]
Hi, i'm using lib and i have problem with Ui (TimePickerDialog)
![device-2017-12-29-111145](https://user-images.githubusercontent.com/14016488/34429321-50ec4726-ec89-11e7-8176-c86e05058c80.png)

Pls fix nó :(  Thanks u every much

**Comment by wdullaer** [comment]
I think this is due to the font that you are forcing on it.
The character spacing and baseline seem off to me.
If you're overwriting the fonts or otherwise messing with internal constants for spacing, you're on your own, there's no way I can make that generic enough that it works in all circumstances.

**Comment by nguyenhuutho** [comment]
Thanks for replied
I'm changed my font and it's working, thanks again <3
