### ISSUE TITLE
Only month and year picker

### ISSUE THREAD

**Issue by DeepakSenapati** [wdullaer/MaterialDateTimePicker#5]
Can this be modified to be used as only month and year picker? I would need this for getting the credit/debit card validity date.

**Comment by wdullaer** [comment]
It could be, but I doubt it is worth the effort.
The year selector is actually pretty well hidden, the day and month selector are combined in a calendar view. I think you'd need to change the entire design to create a decent month/year selector.

In any case, the code is open source, so you're free to give it a shot :-)

**Comment by Vipul12Thawre** [comment]
How to use this lib in eclipse ?

**Comment by wdullaer** [comment]
@Vipul12Thawre please create a new separate issue instead of poluting existing ones.

You can find more information on android library modules [here](https://developer.android.com/tools/projects/index.html#LibraryModules) and [here](http://www.vogella.com/tutorials/AndroidLibraryProjects/article.html#librarymodules)

**Comment by nikhil8500** [comment]
In a calendar pick i would selected all dates but i want to display only month and year in a Textview. plzz help me
