### ISSUE TITLE
A method for change Dateformat

### ISSUE THREAD

**Issue by pranavagiligar** [wdullaer/MaterialDateTimePicker#502]
Please add some public method to DatePickerDialog for change DateFormat of MONTH_FORMAT, YEAR_FORMAT and DAY_FORMAT objects. SO that we can program number of char in mSelectedMonthTextView variable.    "This is not required for locale=english, but in some other languages we have to set **full month name,**"

**Comment by wdullaer** [comment]
I'm using the built in formatter, which should return a string that makes sense in all supported locales.
(For example in Dutch it returns a string of length 4 rather than 3 when using `MMM`)

I'm reluctant to add this option, because it's an option I can't test myself. I will have no idea that a layout change I will do will actually make sense or end up in weird truncation errors in different locales / for different string patterns.

People have forked this library to support different locales which had requirements that were hard to elegantly support with the current codebase (either because they were technically hard, or because I lack the cultural knowledge to properly assess them).
I am more than happy to point to any such forks from the README.

**Comment by pranavagiligar** [comment]
I understood. Thanks for the reply.
