### ISSUE TITLE
Update to given date.

### ISSUE THREAD

**Issue by Shouheng88** [wdullaer/MaterialDateTimePicker#537]
Hello, project owner! Thanks for your work. And here is a little problem:
The `android.app.DatePickerDialog` has one method named `updateDate(int,int,int)` by witch we can update current showing date. But I din't find one with the same function in this library. Is there any method support this function?
--Regards

**Comment by wdullaer** [comment]
You can set an initial selection through the `newInstance()` method, but there is no method to update the selection after you're showing the Dialog.
I haven't added this, because I don't really see a usecase for it: if you update the selection after the Dialog is shown, you risk overwriting a user's selection, which is rather bad UX in my book.

I would need to have some more information on your usecase to see whether that's the case here.

**Comment by Shouheng88** [comment]
I agree. 
But my product manager wants to add a third button to the bottom witch is used to navigate to today. I noticed that the `onDayOfMonthSelected(int,int,int)` method was called in `onDayTapped(CalendarDay)`, witch is used to update the selection UI. I added a third button into the bottom layout and called the `onDayOfMonthSelected(int,int,int)` method when the click event is invoked, then the problem was solved. Is there any risk of calling this method directly?

**Comment by wdullaer** [comment]
I assume that means you have a fork of the library, so you can do what you want ;-)

That's a good solution, it'll do what you want.
I don't consider that callback to be part of the "public API", but it's also highly unlikely to change. It will be easy enough to keep tracking this repository should you want to.

Adding an additional button is something I don't intend on supporting anyway. There are way too many things people would like to do with that. And once I add in a third customizable button, someone is going to turn up wanting a fourth etc.

**Comment by Shouheng88** [comment]
I agree with you. This an awesome project and it helped me a lot. 
Thanks again.

**Comment by wdullaer** [comment]
I'm happy it was useful to you. Good luck!
