### ISSUE TITLE
TimepointLimiter API documentation

### ISSUE THREAD

**Issue by m3dw3** [wdullaer/MaterialDateTimePicker#566]
When creating a custom `TimepointLimiter` it's hard to guess how the required functions should be implemented. I was only able to achieve the desired behaviour by trial and error or guessing. `DefaultTimepointLimiter` implementation also doesn't help much.

Documentation both on the class and methods should explain what a proper implementation for a desired behaviour is (by example). Method documentation should explain why a method is called and how its return value is used.

**Comment by wdullaer** [comment]
Implementing your own TimepointLimiter is considered an expert feature. It's an escape valve, because I can't possible support all use cases.
I haven't spent a lot of time on documentation for this, because of this.

That said, we can always do better. I'll try to add some comments on the interface definition that provides some more information.

**Comment by ElyDantas** [comment]
I successfully disable custom timepoints at isOutOfRange method, they are gray now, but I can't get it to block user from spinning ui starting from valid timepoints and ending in disabled timepoints from isOutOfRange, which method should I change to make it not selectable when user trick ui?
