### ISSUE TITLE
Different fonts on dark/light theme

### ISSUE THREAD

**Issue by ItzNotABug** [wdullaer/MaterialDateTimePicker#569]
I see that when I pass the setThemeDark(true); , then the Timer Text has a different font than the Timer text in the light theme..

![](https://i.imgur.com/sOTYA3r.png)
![](https://i.imgur.com/s7x8s3G.png)

The issue happens on all the versions of Emulators: API 21 to API 27
Screenshot recorded on: API 28 (Real Device)

**Comment by wdullaer** [comment]
I can't find a reason why this is happening. Nothing in that view is conditional on isThemeDark (it is effectively the same in either mode).

Based on the screenshots it looks you have been tinkering with the default fonts, maybe something in your code is not properly applying that font override in the dark theme path. The hour and minute views are framework TextViews, rather than AppCompatTextViews. I intend to rectify that shortly, but it might help in your search.

**Comment by ItzNotABug** [comment]
I ended up tweaking the Time Label TextView's style..
Also, thanks for the great library.. :D
