### ISSUE TITLE
Question - A help on API -14?

### ISSUE THREAD

**Issue by Suall1969** [wdullaer/MaterialDateTimePicker#74]
This is not an issue since Android 2.3 is a pretty old platform and trying to support is on our own. This is more of a friendly need for help.
I managed to port the time picker dialog back compatible to API 10 simply by using AppCompat and NineOldAndroids. (And also some Build Version checks of course.) It is working fine but after choosing hour, RadialPickerLayout doesn't enter the minute chooser although animation takes place.
More precisely, after choosing hour, RadialTextsView disappear but same one appear again, not the minute ones.
Do you think it might be related to the current code?

**Comment by wdullaer** [comment]
I don't think I can help you here a lot.
This library started as a fork from the open source google date and timepicker. I have never touched that part of the code.

Both the time pickerviews are instances of the same class. The picker figures out what exact values to draw based on an index. Most likely you messed up the index somewhere, passing in `HOUR_INDEX` instead of `TIME_INDEX`.
The best you can do is set a breakpoint in `setCurrentItemShowing()` in the `RadialPickerLayout` and step through the code to see what exactly is going on.

**Comment by Suall1969** [comment]
It is only happening on API 10.
As you said, I'll have to do more debugging.
Thanks for the tip.

**Comment by Thore1954** [comment]
The problem is with the getDisappearAnimator & getReappearAnimator in RadialTextsView class.
You'll need to wrap your view with an AnimatorProxy if the running platform needs to be proxied.
so use:
`mDisappearAnimator = ObjectAnimator.ofPropertyValuesHolder(
                AnimatorProxy.NEEDS_PROXY ? AnimatorProxy.wrap(this) : this, radiusDisappear, fadeOut)
                .setDuration(duration);`
instead of:
`mDisappearAnimator = ObjectAnimator.ofPropertyValuesHolder(
                this, radiusDisappear, fadeOut).setDuration(duration);`

**Comment by Suall1969** [comment]
Thank's @Thore1954 
it worked!
