### ISSUE TITLE
Both DatePicker and TimePicker dismiss on orientation change or any view rebuilding event.

### ISSUE THREAD

**Issue by jgall** [wdullaer/MaterialDateTimePicker#76]
Being that the OnDateChangedListener does not allow recalling of the dates that are currently selected in the datepicker, there is no way to get around this by rebuilding the Dialog without losing data. (Part of this is due to a bug in DialogFragment documented here: https://code.google.com/p/android/issues/detail?id=17423&q=setRetaininstance&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars )

**Comment by jgall** [comment]
if the view were passed in to the onDateChaged() interface method, I could potentially work around this myself by using getSelectedDay().

**Comment by wdullaer** [comment]
I'm not sure what you're trying to say here.
The dialogs retain their state on rotation changes just fine.

They do lose their pointers to the callbacks though. There is no way for me to retain them in the dialogs because they might not implement `Parcelable`.

You should set them again in the `onResume()` callback of your activity. See the second answer here http://stackoverflow.com/questions/12822250/dialogfragment-callback-on-orientation-change

I could add this to the sample and make this more clear in the documentation.

**Comment by jgall** [comment]
I am not the most experienced with Android development, but perhaps my issue stems from the fact that I am creating the DatePicker from within another custom Fragment? For whatever reason, when I rotate the device I lose both the min and max dates within the DatePicker as well as my listener connections to my custom Fragment.

**Comment by wdullaer** [comment]
Losing min max dates was a bug in a previous version. Ensure you've got the latest one in your project.

Losing the listener connections is indeed an issue, but it can't be resolved from the library, because the listeners might not implement parcelable.
You should set your listeners again in the onResume() of your custom fragment which calls the dialog. The stackoverflow link I've posted contains some more information on how this is done.

**Comment by jgall** [comment]
I am simply using the maven repository but do not have the update with the bug fix. Is the maven one outdated? Should I use the source instead? 

Thanks so much for your time!

**Comment by wdullaer** [comment]
v1.4.2 is the latest one. This version is available on maven.
Make sure your build.gradle dependencies are up to date.

If they are you can try to do a build clean.
