### ISSUE TITLE
TimePickerDialog - Make selected number text color = white

### ISSUE THREAD

**Issue by anthonynosek** [wdullaer/MaterialDateTimePicker#9]
I think the selected time (hour or minute) should have a white font color to remain consistent with the date picker. At the moment the font color remains black within the selection circle, this can look unattractive when using a dark theme color.

Great project BTW!

**Comment by wdullaer** [comment]
I know, it's on the todo list (as you can see in the readme)
It is not trivial however: the selector in the time pickers can partially cover a number. Do I keep it white, or black or do I try to figure out the bits that are covered and render those white?
I haven't found an elegant solution yet, which is why I've settled for keeping everything black at the moment.

**Comment by anthonynosek** [comment]
Good point, I guess we could introduce another color parameter which specifies the circle fill. At the moment, if a slightly darker color scheme is used the number becomes harder to read. A specific color just for the circle would allow a user to adopt a light color which will no longer require a change of text color. This is a tidy (and easy) solution. 

Thoughts?
